export const capitals = [
  "Andorra la Vella",
  "Abu Dhabi",
  "Kabul",
  "Saint John's",
  "The Valley",
  "Tirana",
  "Yerevan",
  "Luanda",
  "Buenos Aires",
  "Pago Pago",
  "Vienna",
  "Canberra",
  "Oranjestad",
  "Mariehamn",
  "Baku",
  "Sarajevo",
  "Bridgetown",
  "Dhaka",
  "Brussels",
  "Ouagadougou",
  "Sofia",
  "Manama",
  "Bujumbura",
  "Porto-Novo",
  "Gustavia",
  "Hamilton",
  "Bandar Seri Begawan",
  "Sucre",
  "Kralendijk",
  "Brasília",
  "Nassau",
  "Thimphu",
  "Gaborone",
  "Minsk",
  "Belmopan",
  "Ottawa",
  "West Island",
  "Kinshasa",
  "Bangui",
  "Brazzaville",
  "Bern",
  "Yamoussoukro",
  "Avarua",
  "Santiago",
  "Yaoundé",
  "Beijing",
  "Bogotá",
  "San José",
  "Havana",
  "Praia",
  "Willemstad",
  "Flying Fish Cove",
  "Nicosia",
  "Prague",
  "Berlin",
  "Djibouti",
  "Copenhagen",
  "Roseau",
  "Santo Domingo",
  "Algiers",
  "Quito",
  "Tallinn",
  "Cairo",
  "El Aaiún",
  "Asmara",
  "Madrid",
  "Addis Ababa",
  "Helsinki",
  "Suva",
  "Stanley",
  "Palikir",
  "Tórshavn",
  "Paris",
  "Libreville",
  "London",
  "St. George's",
  "Tbilisi",
  "Cayenne",
  "St. Peter Port",
  "Accra",
  "Gibraltar",
  "Nuuk",
  "Banjul",
  "Conakry",
  "Basse-Terre",
  "Malabo",
  "Athens",
  "King Edward Point",
  "Guatemala City",
  "Hagåtña",
  "Bissau",
  "Georgetown",
  "City of Victoria",
  "Tegucigalpa",
  "Zagreb",
  "Port-au-Prince",
  "Budapest",
  "Jakarta",
  "Dublin",
  "Jerusalem",
  "Douglas",
  "New Delhi",
  "Diego Garcia",
  "Baghdad",
  "Tehran",
  "Reykjavik",
  "Rome",
  "Saint Helier",
  "Amman",
  "Tokyo",
  "Nairobi",
  "Bishkek",
  "Phnom Penh",
  "South Tarawa",
  "Moroni",
  "Basseterre",
  "Pyongyang",
  "Seoul",
  "Kuwait City",
  "George Town",
  "Astana",
  "Vientiane",
  "Beirut",
  "Castries",
  "Vaduz",
  "Colombo",
  "Monrovia",
  "Maseru",
  "Vilnius",
  "Luxembourg",
  "Riga",
  "Tripoli",
  "Rabat",
  "Monaco",
  "Chișinău",
  "Podgorica",
  "Marigot",
  "Antananarivo",
  "Majuro",
  "Skopje",
  "Bamako",
  "Naypyidaw",
  "Ulan Bator",
  "Saipan",
  "Fort-de-France",
  "Nouakchott",
  "Plymouth",
  "Valletta",
  "Port Louis",
  "Malé",
  "Lilongwe",
  "Mexico City",
  "Kuala Lumpur",
  "Maputo",
  "Windhoek",
  "Nouméa",
  "Niamey",
  "Kingston",
  "Abuja",
  "Managua",
  "Amsterdam",
  "Oslo",
  "Kathmandu",
  "Yaren",
  "Alofi",
  "Wellington",
  "Muscat",
  "Panama City",
  "Lima",
  "Papeetē",
  "Port Moresby",
  "Manila",
  "Islamabad",
  "Warsaw",
  "Saint-Pierre",
  "Adamstown",
  "San Juan",
  "Ramallah",
  "Lisbon",
  "Ngerulmud",
  "Asunción",
  "Doha",
  "Saint-Denis",
  "Bucharest",
  "Belgrade",
  "Moscow",
  "Kigali",
  "Riyadh",
  "Honiara",
  "Victoria",
  "Khartoum",
  "Stockholm",
  "Singapore",
  "Jamestown",
  "Ljubljana",
  "Longyearbyen",
  "Bratislava",
  "Freetown",
  "City of San Marino",
  "Dakar",
  "Mogadishu",
  "Paramaribo",
  "Juba",
  "São Tomé",
  "San Salvador",
  "Philipsburg",
  "Damascus",
  "Lobamba",
  "Cockburn Town",
  "N'Djamena",
  "Port-aux-Français",
  "Lomé",
  "Bangkok",
  "Dushanbe",
  "Fakaofo",
  "Dili",
  "Ashgabat",
  "Tunis",
  "Nuku'alofa",
  "Ankara",
  "Port of Spain",
  "Funafuti",
  "Taipei",
  "Dodoma",
  "Kyiv",
  "Kampala",
  "Washington D.C.",
  "Montevideo",
  "Tashkent",
  "Vatican City",
  "Kingstown",
  "Caracas",
  "Road Town",
  "Charlotte Amalie",
  "Hanoi",
  "Port Vila",
  "Mata-Utu",
  "Apia",
  "Pristina",
  "Sana'a",
  "Mamoudzou",
  "Pretoria",
  "Lusaka",
  "Harare",
] as const;
